//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';

// home music
export const LOADING_GET_DATA_MUSIC = 'LOADING_GET_DATA_MUSIC';
export const GET_DATA_MUSIC_SUCCESS = 'GET_DATA_MUSIC_SUCCESS';
export const GET_DATA_MUSIC_FAILED = 'GET_DATA_MUSIC_FAILED';
export const GET_DATA_MUSIC = 'GET_DATA_MUSIC';

// loading app music
export const MUSIC_ENABLE_LOADER = 'MUSIC_ENABLE_LOADER';
export const MUSIC_DISABLE_LOADER = 'MUSIC_DISABLE_LOADER';

// list paging music
export const LOADING_GET_DATA_SONG = 'LOADING_GET_DATA_SONG';
export const GET_DATA_SONG_SUCCESS = 'GET_DATA_SONG_SUCCESS';
export const GET_DATA_SONG_FAILED = 'GET_DATA_SONG_FAILED';
export const GET_DATA_SONG_PAGING = 'GET_DATA_SONG_PAGING';

//detail music tracks
export const LOADING_GET_DETAIL_SONG = 'LOADING_GET_DETAIL_SONG';
export const GET_DETAIL_SONG_SUCCESS = 'GET_DETAIL_SONG_SUCCESS';
export const GET_DETAIL_SONG_FAILED = 'GET_DETAIL_SONG_FAILED';
export const GET_DETAIL_SONG = 'GET_DETAIL_SONG';